branch-defaults:
  master:
    environment: aptsocialwebsite-prod
global:
  application_name: AptSocialWebsite
  default_ec2_keyname: timothytooth
  default_platform: 64bit Amazon Linux 2015.03 v1.4.3 running PHP 5.6
  default_region: us-east-1
  profile: eb-cli
  sc: git
